print("Hello! Today I will tell you a story about a dog and his owner.")
print("Before I begin telling the story, I have a few questions for you to answer.")
print("After typing the answer, please press the enter key to continue.")
print("\nPress the enter key to continue...")

ownerName = input("\nWhat is your name:  ")
ownerAge = input("\nWhat is your age:  ")
dogName = input("\nWhat is your dog's name:  ")
dogAge = input("\nWhat is your dog's age:  ")
dogBreed = input("\nWhat is your dog's breed:  ")
favoriteTreat = input("\nWhat is your dog's favorite treat:  ")

print("\nLet us begin the story.")

print("\nThere once lived a beautiful", dogBreed, "named", dogName + ".")
print(dogName, "lived with their owner", ownerName, "in a beautiful neighborhood.")
print(dogName, "was", dogAge, "years old and even thought he was sometimes lazy, he loved to workout.")
print("Today", dogName, "didn't seem lazy at all, but very energetic.")
print(ownerName, "had to figure out how to get rid of the excess energy", dogName, "had.")
print(ownerName, "is", ownerAge, "years old and thinks exercise for both is of great benefit.")
print(ownerName, "decides it is time to have a workout with his", dogBreed, ".")
print("\n")
print(ownerName, "and", dogName, "decide to start with a jog around their neighborhood.")
print("Fifteen minutes later", ownerName, "spots a big open field.")
print(dogName, "saw what", ownerName, "was looking at and started barking with exitement.")
print(ownerName, "decides it is time for", dogName, "to do some sprints and heads to the open field.")
print(ownerName, "pulls out a tennis ball and throws it far across the field.")
print(dogName, "sprints toward the tennis ball, picking it up and bringing it back to", ownerName, ".")
print(ownerName, "keeps playing fetch with his dog for about an hour before he decides his", dogBreed, "had enough exercise.")
print("They both head back home.")
print("\n")
print("As soon as they both arrive home,", dogName, "drinks water and heads off to his bed to take a nap.")
print("After a long two-hour nap,", dogName, "wakes up and barks at", ownerName, "and the tv, indicating he wants to watch tv.")
print(ownerName, "finds a channel about his", dogBreed, "and gives", dogName, favoriteTreat, "for being such a good dog with his workout today.")
print("The", favoriteTreat, "is the dog's favorite and his incredibly happy eating it and watching tv.")
print("\n")
print("Outside it looks like the sun is about to set.")
print(ownerName, "wants to go for a walk around the neighborhood with his", dogBreed, ".")
print(dogName, "refuses to budge after", ownerName, "tries to take him outside.")
print("In the end", ownerName, "promises", dogName, "that he will give him", favoriteTreat, ".")
print("This makes", dogName, "agree to go on a walk and they both head out for a walk as the sun sets.")
print("When they both arrive back home", dogName, "receives a lot of", favoriteTreat, ".")
print("\n")
print("Today was a wonderful day.")
print(dogName, "spent his day happily with", ownerName, ".")
print(dogName, "is a wonderful", dogBreed, ".")
print("Today", dogName, "had an outstanding workout doing 60-minute fetch sprints and later a short walk around the neighborhood enjoying the sunset with", ownerName, ".")
print("\n")
print("The end. Thank you for reading.")
print("Hello.")
